language: java
jdk:
  - openjdk10

before_install:
  - ./gradlew tasks
  
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

install: ./gradlew build
script: ./gradlew check publishAllPublicationsToLocalRepository

deploy:
  - provider: script
    script: ls ./build/libs/
    edge: true
  - provider: script
    script: ls -R ./mcmodsrepo/
    edge: true
  - provider: script
    script: cat ./mcmodsrepo/code/elix_x/mods/boombarrels/Exploding-Barrels/0.0.0-alpha0-1.15.2/Exploding-Barrels-0.0.0-alpha0-1.15.2.pom
    edge: true
  - provider: releases
    token:
      secure: $GITACCESSTOKEN
    file_glob: true
    file: "build/libs/*.jar"
    on:
      tags: true
    edge: true
  - provider: script
    script: ./gradlew curseforge
    on:
      tags: true
    edge: true
