language: java
jdk:
  - openjdk10
  
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

deploy:
  - provider: releases
    token:
      secure: $GITACCESSTOKEN
    file_glob: true
    file: "build/libs/*.jar"
    on:
      tags: true
  - provider: script
    script: ./gradlew curseforge
    on:
      tags: true
